# Assignment 03
## 학번 : 2021305082
## 성명 : 최재륜
### 제출일 : 2026.03.27

## 1. 교재 p.209~p.210에 있는 연습 문제의 각 문제를 Markdown으로 나타내고 그 답을 작성하여 Jupyter Notebook 파일로 제출.

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("food_consumption.csv")
df

## 2. 아래 각 문제에 대해 답을 작성하여 Jupyter Notebook 파일로 제출.

### (1) 첨부한 “서울시 대기질 자료 제공_2020-2021.csv” 파일을 읽어 데이터프레임(pm_df)에 저장하시오(단, 일시 열은 날짜시간 형식으로 저장).

In [23]:
import pandas as pd

pm_df = pd.read_csv('서울시 대기질 자료 제공_2020-2021.csv', encoding='cp949', parse_dates=['일시'])

### (2) pm_df에서 PM25 컬럼을 제거하시오.

In [24]:
pm_df = pm_df.drop(columns=['초미세먼지(PM25)'])

pm_df

                        일시   구분  미세먼지(PM10)
0      2021-12-31 23:00:00   평균        21.0
1      2021-12-31 23:00:00  강남구        21.0
2      2021-12-31 23:00:00  강동구        25.0
3      2021-12-31 23:00:00  강북구        23.0
4      2021-12-31 23:00:00  강서구        28.0
...                    ...  ...         ...
456137 2020-01-01 00:00:00  용산구        12.0
456138 2020-01-01 00:00:00  은평구        18.0
456139 2020-01-01 00:00:00  종로구        20.0
456140 2020-01-01 00:00:00   중구        22.0
456141 2020-01-01 00:00:00  중랑구        22.0

[456142 rows x 3 columns]

### (3) pm_df에서 구분의 값이 ‘성북구’를 제외한 모든 행을 제거하시오.

In [25]:
pm_df = pm_df.loc[pm_df['구분'] == '성북구']

pm_df

                        일시   구분  미세먼지(PM10)
17     2021-12-31 23:00:00  성북구        17.0
43     2021-12-31 22:00:00  성북구        16.0
69     2021-12-31 21:00:00  성북구        13.0
95     2021-12-31 20:00:00  성북구        20.0
121    2021-12-31 19:00:00  성북구        18.0
...                    ...  ...         ...
456029 2020-01-01 04:00:00  성북구        27.0
456055 2020-01-01 03:00:00  성북구        29.0
456081 2020-01-01 02:00:00  성북구        29.0
456107 2020-01-01 01:00:00  성북구        24.0
456133 2020-01-01 00:00:00  성북구        27.0

[17544 rows x 3 columns]

### (4) pm_df에서 결측치의 개수를 보이시오.

In [26]:
pm_df.isnull().sum()

일시              0
구분              0
미세먼지(PM10)    479
dtype: int64

### (5) (3)의 pm_df에서 PM10의 월평균을 구해 데이터프레임 pm10_df에 저장하시오.

In [30]:
pm_df.loc[:,'월'] = pm_df['일시'].dt.month

pm10_df = pm_df.groupby('월')['미세먼지(PM10)'].mean().reset_index()

pm10_df

     월  미세먼지(PM10)
0    1   38.804742
1    2   44.612472
2    3   56.155373
3    4   45.631915
4    5   49.993151
5    6   36.221053
6    7   23.165419
7    8   20.925373
8    9   16.295341
9   10   30.897158
10  11   47.008900
11  12   40.058943

### (6) pm10_df에서 PM10이 가장 높은 달과 낮은 달을 보이시오.

In [36]:
max_month = pm10_df.loc[pm10_df['미세먼지(PM10)'].idxmax()]
min_month = pm10_df.loc[pm10_df['미세먼지(PM10)'].idxmin()]

max_month,min_month

(월              3.000000
 미세먼지(PM10)    56.155373
 Name: 2, dtype: float64,
 월              9.000000
 미세먼지(PM10)    16.295341
 Name: 8, dtype: float64)